### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by slivingston** [MistyCommunity/.NET-SDK#5]
Can you add a license? I think that it would be most useful to include at least:
1. a declaration in the README with a link (e.g., to https://www.apache.org/licenses/LICENSE-2.0)
2. a declaration at the top of [the template source code file SkillTemplate.cs](https://github.com/MistyCommunity/.NET-SDK/blob/ec9fc49c7682d2b486d62daa95aa3cdcacd1856b/C%23/Sample%20Projects/IntroSkills/SkillLibrary/SkillTemplate.cs), which users are likely to build upon.

Thanks!

**Comment by brad-allen** [comment]
Added licenses to a variety of locations and all the new skills.  Let us know if that works for you.

**Comment by slivingston** [comment]
I think there should still be a top-level indication of it. This is traditional practice in open source. For example, in the README or include a file called LICENSE.
